Models/Citas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConsultorioWeb.Models
{
    public class Citas
    {
        public long IdUsuario { get; set; }
        public DateTime FechaCita { get; set; }
        public string HoraCita { get; set; }
    }
}

Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ConsultorioWeb.Controllers
{
    public class CrudController : Controller
    {
        public readonly string api = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"];
        public async Task<dynamic> EliminarUsuario(long id)
        {
            try
            {
                HttpClient client = new HttpClient();
                string apiDelete = api + "/eliminar/usuario" + "?id=" + id;
                HttpResponseMessage message = await client.DeleteAsync(apiDelete);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return ViewBag.ErrorMessage = ex.Message;
            }
        }

        public async Task<dynamic> EliminarCita(long id)
        {
            try
            {
                HttpClient client = new HttpClient();
                string apiDelete = api + "/eliminar/cita" + "?id=" + id;
                HttpResponseMessage message = await client.DeleteAsync(apiDelete);

                return RedirectToAction("Citas", "Lista");
            }
            catch (Exception ex)
            {
                return ViewBag.ErrorMessage = ex.Message;
            }
        }

        public async Task<dynamic> EditarUsuario()
        {
            try
            {
                return RedirectToAction("Index", "Home");

            }
            catch (Exception ex)
            {
                return ViewBag.ErrorMessage = ex.Message;
            }
        }

        public async Task<dynamic> EliminarFoto(long id, string name)
        {
            try
            {
                HttpClient client = new HttpClient();
                string apiDeleteFoto = api + "/eliminar/foto?id=" + id + "&name=" + name;
                HttpResponseMessage httpResponse = await client.DeleteAsync(apiDeleteFoto);
                if (httpResponse.IsSuccessStatusCode)
                {
                    string response = await httpResponse.Content.ReadAsStringAsync();
                    return RedirectToAction("Fotos", "Lista");
                }
                return RedirectToAction("Index", "Home"); //ALERTA DE ERROR
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Controllers/ListaController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ConsultorioWeb.Controllers
{
    public class ListaController : Controller
    {
        public readonly string api = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"];

        public async Task<dynamic> Citas(long id=0)
        {
            try
            {
                HttpClient client = new HttpClient();
                string apiCitas = api + "/buscar/citasxid" + "?id=" + id;
                HttpResponseMessage message = await client.GetAsync(apiCitas);
                if (message.IsSuccessStatusCode)
                {
                    var response = JsonConvert.DeserializeObject(await message.Content.ReadAsStringAsync());
                    ViewBag.Citas = response;
                    return View();
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
            
            return View();
        }

        public async Task<dynamic> Historial(long id = 0)
        {
            try
            {
                HttpClient client = new HttpClient();
                string apiHUsuario= api + "/buscar/usuario" + "?id=" + id + "&fuente=htl";
                HttpResponseMessage message1 = await client.GetAsync(apiHUsuario);
                if (message1.IsSuccessStatusCode)
                {
                    var response1 = JsonConvert.DeserializeObject(await message1.Content.ReadAsStringAsync());
                    ViewBag.Usuario = response1;

                    string apiHAnamnesis = api + "/buscar/anamnesis" + "?id=" + id;
                    HttpResponseMessage message2 = await client.GetAsync(apiHAnamnesis);
                    if (message2.IsSuccessStatusCode)
                    {
                        var response2 = JsonConvert.DeserializeObject(await message2.Content.ReadAsStringAsync());
                        ViewBag.Anamnesis = response2;

                        string apiHFamiliar = api + "/buscar/familiar" + "?id=" + id;
                        HttpResponseMessage message3 = await client.GetAsync(apiHFamiliar);
                        if (message3.IsSuccessStatusCode)
                        {
                            var response3 = JsonConvert.DeserializeObject(await message3.Content.ReadAsStringAsync());
                            ViewBag.Familiar = response3;

                            string apiHEstoma = api + "/buscar/estomatologico" + "?id=" + id;
                            HttpResponseMessage message4 = await client.GetAsync(apiHEstoma);
                            if (message4.IsSuccessStatusCode)
                            {
                                var response4 = JsonConvert.DeserializeObject(await message4.Content.ReadAsStringAsync());
                                ViewBag.Estomatologico = response4;


                                string apiHDental = api + "/buscar/dental" + "?id=" + id;
                                HttpResponseMessage message5 = await client.GetAsync(apiHDental);
                                if (message5.IsSuccessStatusCode)
                                {
                                    var response5 = JsonConvert.DeserializeObject(await message5.Content.ReadAsStringAsync());
                                    ViewBag.Edad = Convert.ToInt32(await new HomeController().BuscarUsuario(Convert.ToInt32(id), "registro"));
                                    ViewBag.Dental = response5;

                                    string apiContabilidad = api + "/contabilidad/consultar?id=" + id;
                                    HttpResponseMessage message6 = await client.GetAsync(apiContabilidad);
                                    if (message6.IsSuccessStatusCode)
                                    {
                                        var response6 = JsonConvert.DeserializeObject( await message6.Content.ReadAsStringAsync());
                                        ViewBag.Contabilidad = response6;
                                    }

                                }
                            }
                        }
                    }
                }

                return View();

            }catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<dynamic> Fotos(long id = 0)
        {
            try
            {
                HttpClient client = new HttpClient();

                string apiFotos = api + "/lista/fotos?id=" + id;
                HttpResponseMessage message = await client.GetAsync(apiFotos);
                if (message.IsSuccessStatusCode)
                {
                    ViewBag.Images = JsonConvert.DeserializeObject(await message.Content.ReadAsStringAsync());
                }
                List<int> list = new List<int>();
                for (int i = 0; i < ViewBag.Images.Count; i++)
                {
                    list.Add(Convert.ToInt32(ViewBag.Images[i].id.Value));
                }

                IEnumerable<int> duplicates = list.GroupBy(x => x)
                                                .Where(g => g.Count() > 1)
                                                .Select(x => x.Key);
                var v = duplicates.Count();

                var c = String.Join(",", duplicates);

                return View();
            }catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

    }
}

Views/Lista/Citas.cshtml
@{
    ViewBag.Title = "Citas";
}

<h2>Lista de citas</h2>
<main>
    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Identificacion</td>
                    <td>Nombre</td>
                    <td>Telefono</td>
                    <td>Fecha de cita</td>
                    <td>Hora de cita</td>
                </tr>
            </thead>
            <tdoy>
                @foreach (var item in ViewBag.Citas)
                {
                    <tr>
                        <td>@item.documento</td>
                        <td>@item.nombre @item.apellido</td>
                        <td>@item.telefono</td>
                        <td>@item.fecha</td>
                        <td>@item.hora</td>
                        <td>
                            <a href="@Url.Action("RegistrarCita","Registro", new { id = item.documento })">
                                <img src="~/Content/Images/Edit.svg" />
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("EliminarCita","Crud", new {id = item.documento})">
                                <img src="~/Content/Images/Delete.svg" />
                            </a>
                        </td>
                    </tr>
                }
            </tdoy>
            <tfoot>

            </tfoot>
        </table>
    </div>
</main>

Views/Lista/Fotos.cshtml
@{
    ViewBag.Title = "Fotos";
}

<h2>FOTOS</h2>
<main>
        @foreach (var item in ViewBag.Images)
        {
            <div class="container">
                <center>
                    <img src="@item.imagen" class="d-block w-50">
                    <a href="@Url.Action("EliminarFoto","Crud", new {id = item.id, name=item.imagen})">
                        <img src="~/Content/Images/Delete.svg" title="Eliminar" />
                    </a>
                </center>
            </div><br />
        }
</main>

Views/Lista/Historial.cshtml
@{
    ViewBag.Title = "Historial";
}

<h2>Historial de paciente</h2>

<main>
    <div class="container">
        <center>
            <p>
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#usuario" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                    Datos de usuario
                </a>
            </p>
        </center>
        <div class="collapse multi-collapse" id="usuario">
            @Html.Partial("~/Views/Partial/_DatosUsuario.cshtml", (object)ViewBag.Usuario)
        </div>
        <center>
            <br />
            <p>
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#amnanesis" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                    Datos de Amnanesis
                </a>
            </p>
        </center>
        <div class="collapse multi-collapse" id="amnanesis">
            @Html.Partial("~/Views/Partial/_DatosAnamnesis.cshtml", (object)ViewBag.Anamnesis)
        </div>
        <br />
        <center>
            <p>
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#familia" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                    Antecedentes personales y familiares
                </a>
            </p>
        </center>
        <div class="collapse multi-collapse" id="familia">
            @Html.Partial("~/Views/Partial/_DatosFamiliar.cshtml", (object)ViewBag.Familiar)
        </div>
        <br />
        <center>
            <p>
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#estomatologico" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                    Examen estomatologico
                </a>
            </p>
        </center>
        <div class="collapse multi-collapse" id="estomatologico">
            @Html.Partial("~/Views/Partial/_DatosEstomatologico.cshtml", (object)ViewBag.Estomatologico)
        </div>
        <br />
        <center>
            <p>
                @if (ViewBag.Edad < 18)
                {
                    <a class="btn btn-primary" data-bs-toggle="collapse" href="#dental" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                        Carta dental niños
                    </a>
                }
                else
                {
                    <a class="btn btn-primary" data-bs-toggle="collapse" href="#dental" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                        Carta dental adultos
                    </a>
                }
            </p>
        </center>
        <div class="collapse multi-collapse" id="dental">
            @Html.Partial("~/Views/Partial/_DatosDental.cshtml", (object)ViewBag.Dental)
        </div>
        <br />
        @if (ViewBag.Contabilidad != null)
        {
            <center>
                <p>
                    <a class="btn btn-primary" data-bs-toggle="collapse" href="#SaldoAbonos" role="button" aria-expanded="false" aria-controls="collapseExample" style="width: 50%;">
                        Contabilidad
                    </a>
                </p>
            </center>
            <div class="collapse multi-collapse" id="SaldoAbonos">
            
                    @Html.Partial("~/Views/Partial/_SaldoAbonos.cshtml", (object)ViewBag.Contabilidad)
            
            </div>
        }
    </div>
</main>