Models/PlanTratamiento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConsultorioWeb.Models
{
    public class PlanTratamiento
    {
        public long IdUsuario { get; set; }
        public string Diagnostico { get; set; }
        public string Pronostico { get; set; }
        public string Tratamiento { get; set; }
        public DateTime Atencion { get; set; }
    }
}

Controllers/TratamientoController.cs
using ConsultorioWeb.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ConsultorioWeb.Controllers
{
    public class TratamientoController : Controller
    {
        public readonly string api = System.Configuration.ConfigurationManager.AppSettings["UrlAPI"];
        StringContent json;

        public ActionResult PlanTratamiento(long id)
        {
            ViewBag.idUsuario = id;
            return View();
        }

        public async Task<dynamic> InsertarTratamiento(List<DateTime> fecha, List<string> diente, List<string> tratamiento
            , List<string> doctor, List<string> firma, string diagnostico, string pronostico, string tratamientos, long idUsuario)
        {
            try
            {
                PlanTratamiento planTratamiento = new PlanTratamiento
                {
                    IdUsuario = idUsuario,
                    Diagnostico = diagnostico,
                    Pronostico = pronostico,
                    Tratamiento = tratamientos,
                    Atencion = DateTime.Now
                };
                HttpClient client = new HttpClient();

                json = new StringContent(JsonConvert.SerializeObject(planTratamiento), Encoding.UTF8, "application/json");
                string apiTrata = api + "/registro/plantratamiento";
                HttpResponseMessage responseUser = await client.PostAsync(apiTrata, json);

                if (responseUser.IsSuccessStatusCode)
                {
                    for (int i = 0; i < fecha.Count; i++)
                    {
                        EstadoTratamiento estado = new EstadoTratamiento
                        {
                            IdUsuario = idUsuario,
                            Fecha = fecha[i],
                            Diente = diente[i],
                            TrataEfectuado = tratamiento[i],
                            Doctor = doctor[i],
                            Firma = firma[i]
                        };
                        json = new StringContent(JsonConvert.SerializeObject(estado), Encoding.UTF8, "application/json");
                        string apiEstado = api + "/registro/estadotratamiento";
                        HttpResponseMessage responseEstado = await client.PostAsync(apiEstado, json);

                        if (responseEstado.IsSuccessStatusCode)
                        {
                        }
                        else
                        {
                            return RedirectToAction("PlanTratamiento", "Registro");
                        }

                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("PlanTratamiento", "Registro");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("PlanTratamiento", "Registro");
            }
        }

    }
}

Views/Tratamiento/CartaDental.cshtml
@{
    ViewBag.Title = "CartaDental";
}

<h2>CartaDental</h2>
<main>
    <div class="container">

    </div>
</main>

Views/Tratamiento/PlanTratamiento.cshtml
@{
    ViewBag.Title = "PlanTratamiento";
    DateTime date = DateTime.Now;
}

<h2>Plan Del Tratamiento</h2>
<main>
    @using (Html.BeginForm("InsertarTratamiento", "Tratamiento", FormMethod.Post))
    {
        <input value="@ViewBag.idUsuario" name="idUsuario" type="text" hidden readonly />
        <br />
        <div class="container">
            <article>
                <table class="table table-striped">
                    <tr>
                        <td>
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroup-sizing-default">DIAGNOSTICO</span>
                            </div>
                            <textarea class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="diagnostico" type="text" rows="5" cols="30"></textarea>
                        </td>
                        <td>
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroup-sizing-default">PRONOSTICO</span>
                            </div>
                            <textarea class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="pronostico" type="text" rows="5" cols="30"></textarea>
                        </td>
                        <td>
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroup-sizing-default">TRATAMIENTO</span>
                            </div>
                            <textarea class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="tratamientos" type="text" rows="5" cols="30"></textarea>
                        </td>
                    </tr>
                    <tr></tr>
                </table>
                <table class="table table-striped" border="1">
                    <thead>
                        <tr>
                            <td>Fecha</td>
                            <td>Diente</td>
                            <td>Tratamiento efectuado</td>
                            <td>Doctor</td>
                            <td>Firma paciente</td>
                        </tr>
                    </thead>
                    <tbody>
                        @**@
                        <tr>
                            <td>
                                <input type="date" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" readonly />
                            </td>
                            <td>
                                <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" readonly />
                            </td>
                            <td>
                                <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" readonly />
                            </td>
                            <td>
                                <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" readonly />
                            </td>
                            <td>
                                <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" readonly />
                            </td>
                        </tr>
                        @**@
                    </tbody>
                </table>
                <table class="table table-striped" id="tblDatos" border="1">
                    <tbody>
                        <tr>
                            <td>
                                <input type="date" name="fecha" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" />
                            </td>
                            <td>
                                <input type="text" name="diente" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Diente" />
                            </td>
                            <td>
                                <input type="text" name="tratamiento" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Tratamiento" />
                            </td>
                            <td>
                                <input type="text" name="doctor" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Doctor" />
                            </td>
                            <td>
                                <input type="text" name="firma" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Firma" />
                            </td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">
                                <center><input type="button" class="btn btn-primary" onclick="insertarFila()" value="Insertar fila" style="width:50%; " /></center>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </article>
            <table class="table table-striped">
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <center><button type="submit" class="btn btn-primary" style="width:50%; ">Guardar</button></center>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    }

    <br />


    <script>
        function insertarFila() {
            let tblDatos = document.getElementById('tblDatos').insertRow(0);
            let col1 = tblDatos.insertCell(0);
            let col2 = tblDatos.insertCell(1);
            let col3 = tblDatos.insertCell(2);
            let col4 = tblDatos.insertCell(3);
            let col5 = tblDatos.insertCell(4);

            col1.innerHTML = '<td><input type="date" name="fecha" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Fecha"/></td>';
            col2.innerHTML = '<td><input type="text" name="diente" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Diente"/></td>';
            col3.innerHTML = '<td><input type="text" name="tratamiento" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Tratamiento"/></td>';
            col4.innerHTML = '<td><input type="text" name="doctor" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Doctor"/></td>';
            col5.innerHTML = '<td><input type="text" name="firma" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" placeholder="Firma"/></td>';
        }
    </script>
</main>